name: Reset Baselines

# Manual trigger + scheduled once each June 25 at 15:00 UTC (8 AM PDT)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 25 6 *'

permissions:
  contents: write

jobs:
  reset-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Reset baselines
        run: node scripts/resetBaselines.js
        env:
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}

      - name: Commit and push updated baseline.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add baseline.json
          git commit -m "chore: reset baseline.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
