name: “Hourly NitroType Update”
on:
  schedule:
    - cron: '0 * * * *'     # top of every hour
  workflow_dispatch:       # allow manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # so we can push

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run scraper & update data
        run: node scripts/update.js

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add baseline.json docs/data.json
          git diff --quiet || git commit -m "ci: update NitroType data"
          git push
