name: Hourly NitroType Update

# ensure the GITHUB_TOKEN has write access to repo contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'    # every hour
  workflow_dispatch:      # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # this tells the action to configure `origin` with GITHUB_TOKEN
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Run scraper
        env:
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: node scripts/update.js

      - name: Commit & push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add baseline.json docs/data.json
          git diff --quiet || git commit -m "ci: update NitroType data"
          git push
